services:
  - type: web
    name: unreliable-unicorn-front
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://unreliableunicorn-api.onrender.com
      - key: VITE_API_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /(.*)?
        destination: /index.html
